---
title: "Reporte de control de calidad y exploración de bases de datos ecológicas"
format: html
---

**Reporte de control de calidad**

-   **Principales problemas detectados:** El nombre de las especies se encontraba escrito de manera incorrecta en un par de ocasiones, de igual manera habían individuos sin registro (NA) como el caso de la variable *sex*, variables morfométricas y la columna de *comments.*

-   **Cambios aplicados:** Se aplicó una homogenización a los nombres, se corrigió los que se encontraban escritos incorrectamente y se añadieron al grupo de especie correspondiente, estandarizando todos los nombres en minúscula. También se agregó una columna de la variable *sex (sex clean)* la cual cambió los NA por *uknow* para no crear sesgos en el proceso.

```{r}
datos_limpios |> 
  count(Species)
```

-   **Sin corregir:** No se eliminaron los NA de las diferentes variables, ya que no se desea tener sesgos por muestreos faltantes, tanto para la columna de *comments*, la cual no intervenía en los datos, tratándose de una variable completamente descriptiva.

-   **Cómo reproducir tu resultado:**
